name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  go_router: ^14.2.1
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
